apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: bulletin-board
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # доступен снаружи кластера на порту 30080
  type: NodePort
