apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bulletin-board
type: Opaque
# Значения закодированы в base64: echo -n "postgres" | base64
stringData:
  POSTGRES_DB: bulletin_board
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bulletin_board
